swagger: '2.0'
info:
  title: Express-Sequelize-Passport-Example-API
  version: 1.0.0
host: 'localhost:3000'
basePath: /
paths:
  /signup:
    post:
      summary: Add User to database
      produces: 
        - application/json
      parameters:
        - in : query
          name: email
          type: string
          required: true
          description: User's email address
        - in: query
          name: password
          type: string
          required: true
          description: User's password
      responses:
        200:
          description: Returns User's Object
          schema:
            type: object
            properties:
              message: 
                type: string
                example: "Signup Successful"
              user:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  email:
                    type: string
                    example: abc@xyz.com
                  password:
                    type: string
                  billing_id:
                    type: integer
                    example: 1