swagger: "2.0"
info:
  title: E-Commerce REST API
  version: 1.0.0  
host: localhost:3000
basePath: /
securityDefinitions:
  Token:
    type: apiKey
    name: secret_token
    in: query
    
paths:
  /signup:
    post:
      summary: Add User to database
      parameters:
        - in : query
          name: email
          required: true
          description: User's email address
          type: string
        - in: query
          name: password
          required: true
          description: User's password
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Returns User's Object
          schema:
            type: object
            properties:
              message: 
                type: string
                example: "Signup Successful"
              user:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  email:
                    type: string
                    example: abc@xyz.com
                  password:
                    type: string
                  billing_id:
                    type: integer
                    example: 1
      tags:
        [Auth]
  
  /login:
    post:
      summary: Login to Application
      parameters:
        - in : query
          name: email
          required: true
          description: User's email address
          type: string
          
        - in: query
          name: password
          required: true
          description: User's password
          type: string
      produces:
        - application/json
      responses:
        200:
          description:  Returns Unique Token
          schema:
            type: object
            properties:
              token:
                type: string
      tags:
        [Auth]
  
  /products/{productId}:
    get:
      summary: Returns a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          type: integer
      produces: 
        - application/json
      responses:
        200:
          description: A product object
          schema:
            type: object
            properties:
              id:
                type: integer
              sku:
                type: integer
              name:
                type: string
              price:
                type: integer
              description:
                type: string
              thumbnail:
                type: string
              image:
                type: string
              category:
                type: string
              stock:
                type: integer
      tags:
        - Products
      security:
        - Token: [] 
    put:
      summary: Update product listing
      consumes:
        - application/json
      parameters:
        - name: productId
          in: path
          required: true
          type: integer
          
        - name: payload
          in: body
          required: true
          description: object
          schema:
            type: object
            properties:
              sku:
                type: integer
              name:
                type: string
              price:
                type: integer
              description:
                type: string
              thumbnail:
                type: string
              image:
                type: string
              category:
                type: string
              stock:
                type: integer
      responses:
        200:
          description: OK
      tags:
        - Products
    delete:
      summary: Delete Product
      parameters:
        - name: productId
          in: path
          required: true
          type: integer
      responses:
        200:
          description: OK
      tags:
        - Products
        
  
  /products:
    get:
      summary: Returns products by category
      parameters:
        - name: category
          in: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: An object of products by category
          schema:
            type: object
      tags:
        - Products
      security:
        - Token: []    
    post:
      summary: Create product
      consumes: 
        - application/json
      parameters:
        - name: Payload
          in: body
          required: true
          description: object
          schema:
            type: object
            properties:
              sku:
                type: integer
              name:
                type: string
              price:
                type: integer
              description:
                type: string
              thumbnail:
                type: string
              image:
                type: string
              category:
                type: string
              stock:
                type: integer
      responses:
        200:
          description: OK
      tags:
        - Products
      security:
        - Token: []
        
    
        
      
